name: 'Publish package to NPM'

on:
  release:
    types: ['created']

jobs:
  run-tests:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'pnpm/action-setup@v2'
        with:
          version: 7
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'pnpm'
      - run: 'pnpm install'

  publish-npm:
    needs: 'run-tests'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'pnpm/action-setup@v2'
        with:
          version: 7
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'
      - run: 'pnpm install'
      - run: 'pnpm package:build'
      - run: 'pnpm compile-css'
      - run: 'cd package'
      - run: 'pnpm publish --no-git-checks --access=public'
        env:
          NODE_AUTH_TOKEN: '${{secrets.NPM_ACCESS_TOKEN}}'
